### ISSUE TITLE
cant get the pretrained model

### ISSUE THREAD

**Issue by flygyyy** [peterliht/knowledge-distillation-pytorch#1]
cant open the url to get the pretrained teacher model checkpoints, can you offer another way??

**Comment by haitongli** [comment]
an alternative folder link:
https://office365stanford-my.sharepoint.com/:u:/g/personal/haitongl_stanford_edu/ESqCguWIU1JHoMJJyu8eDIABcp9UX5VzPp1VQvhzNjllGw?e=HMPjwA

let me know if this works (if you can access Box.com and/or Onedrive, both original README link and this one should work fine)

**Comment by flygyyy** [comment]
the link works fine, thanks
