### ISSUE TITLE
Box folder

### ISSUE THREAD

**Issue by zihaozhang9** [peterliht/knowledge-distillation-pytorch#14]
请问我在服务器上如何通过linux命令下载 box文件夹中的数据？

**Comment by zihaozhang9** [comment]
Hello! I can't download the model. Is there any other download address?

**Comment by haitongli** [comment]
> Hello! I can't download the model. Is there any other download address?

Can you give more details regarding why you couldn't download the model? Can you access either Box or google drive?

**Comment by Khumayun** [comment]
Hello. Having same issue. Box folder is not available if you go by link given in readme.md file (https://stanford.app.box.com/s/5lwrieh9g1upju0iz9ru93m9d7uo3sox). Can you publish it on google drive ?

**Comment by zihaozhang9** [comment]
我已收到您发送的邮件。我会及时查看。

**Comment by Khumayun** [comment]
@zihaozhang9 Do you have the model ? I think there is no link other than stanford.app.box.com, where the file is not available.

**Comment by haitongli** [comment]
A new link for downloading the zip folder is updated in readme.
