### ISSUE TITLE
boxed folder

### ISSUE THREAD

**Issue by mlszy928** [peterliht/knowledge-distillation-pytorch#26]
I have downloaded the .zip file from boxed folder, but it can't be unzipped successfully, after being unzipped, the .tar file has become .tar.cpgz file. I also have tried to unzipped through 'unzip' and 'tar xvf' through terminal on max OSX, but failed. II 
<img width="747" alt="屏幕快照 2020-04-16 下午10 14 28" src="https://user-images.githubusercontent.com/30581867/79467350-43a69e80-8030-11ea-9d37-81911f357fb5.png">
<img width="682" alt="屏幕快照 2020-04-16 下午10 14 56" src="https://user-images.githubusercontent.com/30581867/79467364-4903e900-8030-11ea-8444-236f53def737.png">
<img width="682" alt="屏幕快照 2020-04-16 下午10 14 41" src="https://user-images.githubusercontent.com/30581867/79467401-528d5100-8030-11ea-9687-84c28674d920.png">
Could you please send me the boxed folder file to my email? 15371254460@163.com Thank You!

**Comment by LLeeSG** [comment]
met similar problem, can't unzip best.pth.tar properly, could anyone help?
![2020-06-16_150603](https://user-images.githubusercontent.com/16949144/84742628-52cfab80-afe3-11ea-8d9f-3571b5fbb678.PNG)

**Comment by lleesg** [comment]
met similar problem, can't unzip best.pth.tar properly, could anyone help?
![2020-06-16_150603](https://user-images.githubusercontent.com/16949144/84742681-6c70f300-afe3-11ea-808e-dccc136df85f.PNG)

**Comment by parquets** [comment]
> met similar problem, can't unzip best.pth.tar properly, could anyone help?
> ![2020-06-16_150603](https://user-images.githubusercontent.com/16949144/84742681-6c70f300-afe3-11ea-808e-dccc136df85f.PNG)

do you solve the problem?

**Comment by haitongli** [comment]
A new link for downloading the zip folder is updated in readme.
