### ISSUE TITLE
How to improve studentmodel's acc?

### ISSUE THREAD

**Issue by RichardMrLu** [peterliht/knowledge-distillation-pytorch#5]
My teachermodel's acc is 99%, but when I try to distill knowledge, my studentmodel's acc is under 10%. It seems that studentmodel didn't learn knowledge from teachermodel.
I use Lenet5 as my studentmodel,alpha = 0.9, temperature = 1.
Thanks for your help.

**Comment by RichardMrLu** [comment]
Dataset is GTSRB, 43 classes.

**Comment by husheng876** [comment]
Have you solved this problem? How it can be done
